# -*- coding: utf-8 -*-
"""yolov8test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlWYcrHNMeCPRpFz5lcf1W63sxlySAYf
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
import torch
import os

!wget -O dataset.zip "https://app.roboflow.com/ds/4hnIxFVgKz?key=Zo2Yy7kLwb"
!unzip dataset.zip -d /content/dataset

model = YOLO('yolov8s.pt')

results = model.train(
    data='/content/dataset/data.yaml',
    epochs=100,
    batch=16,
    imgsz=640
)

from google.colab import files

uploaded = files.upload()

model = YOLO('/content/runs/detect/train/weights/best.pt')


result = model.predict('/content/images (3).jpg', save=True)

import cv2
from matplotlib import pyplot as plt

img = cv2.imread('/content/runs/detect/predict3/images (3).jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.show()

